"""create meals, food_items, goals

Revision ID: 519d9751ea12
Revises: 6855d94a861b
Create Date: 2026-07-21 21:30:47.780834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519d9751ea12'
down_revision: Union[str, Sequence[str], None] = '6855d94a861b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('protein_goal', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carb_goal', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_goal', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype', native_enum=False, length=20), nullable=False),
    sa.Column('meal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_meal_id'), 'food_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_meal_id'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_table('goals')
    # ### end Alembic commands ###
